before_script:
  - apt-get update -qq && apt-get install -y -qq cmake make g++
  - uname -a
  - g++ --version
  - cmake --version

stages:
  - test

job 1:
  stage: test
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ctest -V

