before_script:
  - apt-get update -qq && apt-get install -y -qq cmake make
  - cat /etc/debian_release
  - g++ --version
  - cmake --version

image: "gcc:7"

stages:
  - test

job 1:
  stage: test
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ctest -V

