before_script:
  - apt-get -qq update && apt-get install -y -qq cmake make lsb-release
  - lsb_release -a
  - g++ --version
  - cmake --version

image: "gcc:7"

stages:
  - test

job 1:
  stage: test
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ctest -V

